### PR TITLE
Creation of the apps menu

### PR DESCRIPTION
**Pull request by niconoir**
Signed-off-by: NOIR Nicolas ext <nicolas.noir@rte-france.com>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [X] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
This PR adds a new button on the top bar of the application to display available apps in GridSuite

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

### CODE REVIEW

**Comment by geofjamg** [comment]
image

When we click on the app button the (only) item appears to be blue because of focus. Is there a way to avoid this?

Also maybe the icon is a to big?

**Comment by niconoir** [comment]
@mikatheo @geofjamg Do you think the button should appear even if the user is not connected ?

**Comment by mikatheo** [comment]
> @mikatheo @geofjamg Do you think the button should appear even if the user is not connected ?

Good question. I’m for a pragmatic approach : no button if I’m not connected, because not usable.

**Comment by niconoir** [comment]
> 
> When we click on the app button the (only) item appears to be blue because of focus. Is there a way to avoid this?
> 
> Also maybe the icon is a to big?

I agree the icon is maybe too big. I will try to reduce its size. I'll also take a look at the focus behaviour.

**Comment by niconoir** [comment]
> > When we click on the app button the (only) item appears to be blue because of focus. Is there a way to avoid this?
> > Also maybe the icon is a to big?
> 
> I agree the icon is maybe too big. I will try to reduce its size. I'll also take a look at the focus behaviour.

If we remove focus from the Apps menu, the behaviour will be different from the one of the Preferences menu (which automatically gives focus to the first item of the menu). Do we want these two menus to behave differently ? I agree it seems strange to have blue focus on the single item available of the menu, but when there will be more items in the menu, it will make sense...

**Comment by geofjamg** [comment]
> > > When we click on the app button the (only) item appears to be blue because of focus. Is there a way to avoid this?
> > > Also maybe the icon is a to big?
> > 
> > 
> > I agree the icon is maybe too big. I will try to reduce its size. I'll also take a look at the focus behaviour.
> 
> If we remove focus from the Apps menu, the behaviour will be different from the one of the Preferences menu (which automatically gives focus to the first item of the menu). Do we want these two menus to behave differently ? I agree it seems strange to have blue focus on the single item available of the menu, but when there will be more items in the menu, it will make sense...

Yes, agreed

**Pull request merged**
